import React from "react";
import Head from "next/head";
import SignIn from "@/components/signup";
const SignupPage = () => {
  return (
    <>
      <Head>
        <title>Payroll MS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="login">
        <SignIn />
      </main>
    </>
  );
};

export default SignupPage;
